// src/data/simuladorPreload.js
export const situacionesSimuladas = [
  {
    categoria: "Comunicación Interna",
    situacion: "Falta de comunicación entre áreas",
    respuesta1: "Organizar reuniones semanales entre los líderes de cada área.",
    respuesta2: "Implementar una plataforma colaborativa como Slack o Teams.",
    respuesta3: "Asignar un responsable de comunicación interna entre sectores.",
  },
  {
    categoria: "Comunicación Interna",
    situacion: "Rumores que generan mal clima",
    respuesta1: "Hablar abiertamente en reuniones para desmentir rumores.",
    respuesta2: "Fomentar un canal de comunicación donde los empleados puedan consultar directamente.",
    respuesta3: "Capacitar a los líderes para que detecten y gestionen rumores a tiempo.",
  },
  {
    categoria: "Comunicación Interna",
    situacion: "Desconocimiento de objetivos organizacionales",
    respuesta1: "Realizar presentaciones trimestrales sobre los objetivos de la empresa.",
    respuesta2: "Enviar newsletters internos con avances y metas alcanzadas.",
    respuesta3: "Involucrar a los equipos en la definición de metas departamentales.",
  },
  {
    categoria: "Comunicación Interna",
    situacion: "Problemas entre compañeros no comunicados",
    respuesta1: "Fomentar conversaciones uno a uno con mediación del área de RRHH.",
    respuesta2: "Ofrecer talleres de comunicación asertiva para todo el equipo.",
    respuesta3: "Establecer una política de resolución de conflictos internos.",
  },
  {
    categoria: "Comunicación Interna",
    situacion: "Falta de feedback del liderazgo",
    respuesta1: "Implementar evaluaciones regulares con espacio para devoluciones.",
    respuesta2: "Formar a los líderes para que integren el feedback como hábito.",
    respuesta3: "Crear una cultura de retroalimentación informal constante.",
  },

  {
    categoria: "Liderazgo",
    situacion: "Líder autoritario que genera miedo",
    respuesta1: "Capacitación en liderazgo positivo y coaching.",
    respuesta2: "Evaluación 360° para obtener devoluciones del equipo.",
    respuesta3: "Acompañamiento con mentoría desde RRHH.",
  },
  {
    categoria: "Liderazgo",
    situacion: "Falta de liderazgo en equipo técnico",
    respuesta1: "Designar un referente técnico con habilidades blandas.",
    respuesta2: "Brindar formación en liderazgo a técnicos senior.",
    respuesta3: "Implementar liderazgo compartido o rotativo.",
  },
  {
    categoria: "Liderazgo",
    situacion: "Líder que no toma decisiones",
    respuesta1: "Talleres sobre toma de decisiones ágiles.",
    respuesta2: "Acompañamiento con coaching ejecutivo.",
    respuesta3: "Definir roles y responsabilidades más claramente.",
  },
  {
    categoria: "Liderazgo",
    situacion: "Desconfianza en el liderazgo por falta de transparencia",
    respuesta1: "Publicar reportes internos con decisiones tomadas.",
    respuesta2: "Fomentar reuniones abiertas con rendición de cuentas.",
    respuesta3: "Incluir al equipo en el proceso de toma de decisiones.",
  },
  {
    categoria: "Liderazgo",
    situacion: "Jefe que delega mal y sobrecarga al equipo",
    respuesta1: "Capacitación sobre delegación efectiva.",
    respuesta2: "Revisión y redistribución de tareas.",
    respuesta3: "Seguimiento con RRHH sobre carga laboral.",
  },

  {
    categoria: "Evaluación de desempeño",
    situacion: "Empleado desmotivado por falta de feedback",
    respuesta1: "Implementar feedback mensual estructurado.",
    respuesta2: "Hacer reuniones uno-a-uno periódicas.",
    respuesta3: "Formar a líderes en habilidades de comunicación.",
  },
  {
    categoria: "Evaluación de desempeño",
    situacion: "Injusticia percibida en evaluaciones",
    respuesta1: "Diseñar un sistema claro de evaluación por objetivos.",
    respuesta2: "Incluir autoevaluaciones y revisión cruzada.",
    respuesta3: "Auditar evaluaciones con RRHH como garante.",
  },
  {
    categoria: "Evaluación de desempeño",
    situacion: "Evaluaciones que no impactan en decisiones",
    respuesta1: "Vincular resultados a promociones o aumentos.",
    respuesta2: "Comunicar claramente el propósito de las evaluaciones.",
    respuesta3: "Revisar el sistema para hacerlo más accionable.",
  },
  {
    categoria: "Evaluación de desempeño",
    situacion: "Evaluaciones poco frecuentes",
    respuesta1: "Realizar evaluaciones semestrales mínimamente.",
    respuesta2: "Aplicar encuestas breves trimestrales de seguimiento.",
    respuesta3: "Establecer rutinas de check-in mensuales.",
  },
  {
    categoria: "Evaluación de desempeño",
    situacion: "Dificultades para evaluar roles nuevos",
    respuesta1: "Definir KPIs claros para nuevos roles.",
    respuesta2: "Evaluar en base a objetivos pactados por el área.",
    respuesta3: "Realizar evaluaciones cualitativas con feedback grupal.",
  },

  {
    categoria: "Motivación y clima",
    situacion: "Bajo compromiso del equipo",
    respuesta1: "Realizar encuestas de clima laboral.",
    respuesta2: "Lanzar campañas internas de reconocimiento.",
    respuesta3: "Implementar acciones surgidas de reuniones de equipo.",
  },
  {
    categoria: "Motivación y clima",
    situacion: "Ambiente negativo por alta rotación",
    respuesta1: "Detectar causas con entrevistas de salida.",
    respuesta2: "Fortalecer inducción y acompañamiento al ingreso.",
    respuesta3: "Ofrecer desarrollo y oportunidades de crecimiento.",
  },
  {
    categoria: "Motivación y clima",
    situacion: "Falta de sentido del trabajo",
    respuesta1: "Comunicar propósito y valores de la empresa.",
    respuesta2: "Relacionar tareas con el impacto en clientes o comunidad.",
    respuesta3: "Promover espacios de reflexión en equipo.",
  },
  {
    categoria: "Motivación y clima",
    situacion: "Falta de reconocimiento",
    respuesta1: "Implementar programa de reconocimientos mensuales.",
    respuesta2: "Capacitar líderes para reconocer logros en público.",
    respuesta3: "Permitir que pares reconozcan a sus colegas.",
  },
  {
    categoria: "Motivación y clima",
    situacion: "Estrés y sobrecarga constante",
    respuesta1: "Evaluar cargas de trabajo y redistribuir si es necesario.",
    respuesta2: "Fomentar pausas activas y autocuidado.",
    respuesta3: "Definir prioridades y decir no a tareas innecesarias.",
  }
];